### ISSUE TITLE
krepton.desktop has unrecognised options

### ISSUE THREAD

**Issue by mfraser** [martenjj/krepton#2]
The krepton.desktop file has the line:
Exec=krepton -caption "%c" %i %m
to run krepton, but the help file:
add ' "bbc" ' = ' "BBC Repton 3" '
Usage: krepton [options] [episode]
The Repton game for KDE

Options:
  -h, --help                 Displays help on commandline options.
  --help-all                 Displays help including Qt specific options.
  -v, --version              Displays version information.
  --author                   Show author information.
  --license                  Show licence information.
  --desktopfile <file name>  The base file name of the desktop entry for this
                             application.

Arguments:
  episode                    Name of episode to load

Has no mention of the -caption option and this stops it from running.

**Comment by martenjj** [comment]
Thanks for the report, now fixed.
